#!/bin/bash
#
#
uname=$1

echo "***** USER ADD on HTPASSWD *****"
ssh ood sudo scl enable httpd24 -- htpasswd -b /opt/rh/httpd24/root/etc/httpd/.htpasswd $uname $uname
echo "--> Apache Entry Completed."
