#!/bin/bash
#
#
uname=$1
fname=$2

echo "***** USER CREATE on OHPC *****"
useradd -m -s "/bin/bash" -U -d "/home/$uname" -c "$fname" $uname
echo "--> User Created."

#echo "$uname" | passwd --stdin $uname
#echo "--> User Password Created."

wwsh file resync passwd group shadow
echo "--> WareWulf Entry Completed."

sacctmgr -i add user name=$uname account="xcbc-users"
echo "--> Slurm Entry Completed."

echo "***** USER CREATE on OOD *****"
uid=`id -u "$uname"`
gid=`id -g "$uname"`

su - vagrant -c 'ssh ood sudo useradd -M -s "/bin/bash" -u '$uid' -U -c '$fname' '$uname''
echo "--> User Created."

