#!/bin/bash
#
#
uname=$1

echo "***** USER DELETE on HTPASSWD *****"
ssh ood sudo scl enable httpd24 -- htpasswd -D /opt/rh/httpd24/root/etc/httpd/.htpasswd $uname
echo "--> Apache Updation Completed."
